from datetime import timedelta

SCREENWIDTH = 1200
SCREENHEIGHT = 700

# User
USER_SPEED = 3
USER_HEIGHT = 80
USER_WIDTH = 80

# Projectils
INTERVAL_BETWEEN_SHOT = timedelta(seconds=1) 

MAP_HEIGHT_LIMIT = SCREENHEIGHT - USER_HEIGHT
MAP_WIDTH_LIMIT = SCREENWIDTH - USER_WIDTH

# Colors
GREY = (128, 128, 128)
