from datetime import timedelta

SCREENWIDTH = 1200
SCREENHEIGHT = 700

# User
USER_SPEED = 3
USER_HEIGHT = 80
USER_WIDTH = 80

# Projectil
INTERVAL_BETWEEN_SHOT = timedelta(seconds=1) 
NORTH = 0
NORTH_EAST = 1
EAST = 2
SOUTH_EAST = 3
SOUTH = 4
SOUTH_WEST = 5
WEST = 6
NORTH_WEST = 7
POS_X = [0, 2, 3, 2, 0, -2, -3, -2]
POS_Y = [3, 2, 0, -2, -3, -2, 0, -2]

MAP_HEIGHT_LIMIT = SCREENHEIGHT - USER_HEIGHT
MAP_WIDTH_LIMIT = SCREENWIDTH - USER_WIDTH

# Colors
GREY = (128, 128, 128)
